version: '3.8'

services:
  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/usersdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
